# Generated by Django 2.0 on 2018-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romanNumber', models.CharField(max_length=30)),
                ('arabicNumber', models.IntegerField()),
            ],
        ),
    ]
