# Generated by Django 2.0 on 2018-07-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpair',
            name='romanNumber',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
